title: Douglas Fisher
description: Software Technology Development & Leadership
url: https://dfisher95350.github.io
remote_theme: dfisher95350/jekyll-theme
google_analytics: G-8VBXEJ1GS5
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
# comment ..