title: Douglas Fisher
description: Software Technology Development & Leadership
theme: jekyll-theme-slate

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 30
  exclude:
    archived: true
    forks: true
    projects:
  # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: douglas-fisher-0a43971
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username